BOOTSTRAP_HASKELL_NONINTERACTIVE=1
BOOTSTRAP_HASKELL_GHC_VERSION=9.6.7
BOOTSTRAP_HASKELL_CABAL_VERSION=3.12.1.0
BOOTSTRAP_HASKELL_STACK_VERSION=3.3.1
BOOTSTRAP_HASKELL_HLS_VERSION=2.11.0.0
curl --proto '=https' --tlsv1.2 -sSf https://get-ghcup.haskell.org | sh
